- name: Deploy Flask App with Docker
  hosts: web
  become: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Start Docker
      service:
        name: docker
        state: started
        enabled: true

    - name: Pull Docker image
      docker_image:
        name: olegbulka/public-repo
        tag: devops-app-example-1.0-amd64
        source: pull

    - name: Run Docker container
      docker_container:
        name: flaskapp
        image: olegbulka/public-repo:devops-app-example-1.0-amd64
        state: started
        restart_policy: always
        ports:
          - "5000:8000"
